### ISSUE TITLE
PR #152 issues

### ISSUE THREAD

**Issue by W0CHP** [AndyTaylorTweet/Pi-Star_DV_Dash#159]
The calibration page requires `lsof` being present on Pi-Star, which by default, is not. E.g.:

https://github.com/AndyTaylorTweet/Pi-Star_DV_Dash/blob/03afc6b71e191de7dc41e09db92e58b92a0e9664/admin/calibration.php#L16

Additionally, the calibration page's call to netcat (`nc`) is using the `-w0` flag in three instances, resulting in a "invalid wait-time" output. Pi-Star ships with `netcat-traditional/oldstable,now 1.10-41.1` , so I'm unsure if the PR creator's @narspt  `nc` version is different and honors the `-w0` flag. 🤷 
E.g.:

https://github.com/AndyTaylorTweet/Pi-Star_DV_Dash/blob/03afc6b71e191de7dc41e09db92e58b92a0e9664/admin/calibration.php#L30

Ultimately, the calibration page does not work as described in the PR #152 notes (no green indicator after "start" is invoked, unable to select modes) on a pristine Pi-Star 4.1.6 installation.

**Comment by MW0MWZ** [comment]
@narspt - if there are requirements to make this work, let me know and I can push an update to pull them in.

**Comment by narspt** [comment]
Thanks @W0CHP for pointing this, I did just submit a PR to fix the issues. Indeed I have nc.openbsd as default instead of nc.traditional on my Pi-Star, and I do have lsof ... I should have tested it on a clean Pi-Star, sorry :)

@MW0MWZ: No need to include anything extra, I did just change it on new PR to use fuser -k instead of kill/lsof and changed nc arguments to be compatible with both flavors of nc, actually only for the listen nc because for sending udp data I did even better and changed it to native php code, cleaner and faster 😄

**Comment by W0CHP** [comment]
No worries, @narspt. Good woork - PR #162 now functions as described on a default Pi-Star 4.1.6 installation. :-)

**Comment by W0CHP** [comment]
Verified that PR #162 addressed this issue. Thank you @narspt :)
